openhealthcare/elcid

elcid/models.py, elcid/tests/__init__.py, requirements.txt
It seems to run quicker approx twice as fast by rough tests, slight change in directory structure, let me know what you think. 
Also refactored some existing tests to use the existing test user and added a 200 test.
=> 684 csv new lines

elcid/assets/js/elcid/controllers/diagnosis_discharge.js, elcid/templates/elcid/_includes/antimicrobial_multi_form.html, elcid/templates/elcid/_includes/travel_multi_form.html
fix the orders of fields to that described in #747
=> 771 league table

elcid/migrations/0026_labtestdetails.py, elcid/migrations/0027_ridrtistudydiagnosis.py, elcid/models.py, elcid/schema.py, elcid/templates/modals/lab_test_modal.html, elcid/templates/modals/rid_rti_study_diagnosis_modal.html, elcid/templates/records/lab_test.html, elcid/templates/records/rid_rti_study_diagnosis.html
refs openhealthcare/opal-research#72
Tweaks the display of labtest as per https://github.com/openhealthcare/opal-research/issues/71
Adds Study Diagnosis as per https://github.com/openhealthcare/opal-research/issues/74
=> Minor Research updates

data/lookuplists/lookuplists.json, requirements.txt
depend on the latest version of opal, add facial pain to the lookup lists
=> Lookup list changes

CHANGELOG.md, README.md, elcid/dashboards.py, elcid/templates/actions/presenting_complaint.html, elcid/test/test_create_random_data.py, etc/celery.conf, etc/gunicorn.conf, fabfile.py
I'm not sure about the dashboards change, was 6 out of date?
=> V6 merge branch

elcid/models.py, elcid/test/test_models.py
we weren't sending id over to the front end so every post was creating a new presenting complaint
=> presenting complaint fix

walkin/static/js/walkin/controllers/walkin_hospital_number.js
I can't think of a good way to unittest this that would _actually have caught_ the bug.
The place to catch this would have been code review for https://github.com/openhealthcare/opal/commit/ec771bf613193fc2dcb1a931dcdc41ff926958b7#diff-cdf3fd7189bc89bcf7873cffc5150aa5L78 I suspect...
If you can think of a way to test for this that stops it regressing again, do LMK.
I think this is an across the board angular dependencies thing though.
=> Don't even think about schema. That's not a thing any more.

requirements.txt
PR #981 also needed this requirements change !
=> Bump wardround target version

elcid/templates/detail/micro_haem.html
=> Hide episode of neutropenia

elcid/templates/detail/micro_haem.html
admission dates will need to come back in later on.
Fixes #837
=> Just kill episode dates for now -

microhaem/detail.py
The MicroHaem PatientView should be expressed as a `detail.PatientDetailView` now that we have those...
=> Add a MH custom detail view

infectiousdiseases/patient_lists.py
Now that we pull display names from the list classes, we should start setting them!
=> Add display names for infectiousdiseases lists

etc/gunicorn_conf_test.py, etc/test.conf, fabfile.py
Fab deploy will now deploy us to EC2.
Partially fixes #991
=> 991 test deploy

.travis.yml, config/karma.conf.developer.js, config/karma.conf.travis.js, elcid/assets/js/elcid/controllers/diagnosis_add_episode.js, elcid/assets/js/elcid/controllers/diagnosis_hospital_number.js, elcid/assets/js/elcidtest/controllersTest.js, elcid/assets/js/elcidtest/diagnosis_add_episode.controller.test.js, elcid/assets/js/elcidtest/diagnosis_hospital_number.controller.test.js, elcid/fixtures/patients_records.json, opat/static/js/opat/controllers/opat_referral.js, walkin/static/js/walkin/controllers/walkin_hospital_number.js, walkin/static/js/walkintest/walkin_discharge.controller.test.js, walkin/static/js/walkintest/walkin_hospital_number.controller.test.js
We want to pass tags into AddEpisodeCtrl so that we can tag to the current list.
Half fixes #996
=> 996 add patient tagging

elcid/templates/forms/demographics_form.html
=> Update demographics form to make editing DOB a datepicker

walkin/templates/modals/clinical_findings_modal.html
=> Convert problematic fields to use {% forms %}

elcid/templates/detail/micro_haem.html
=> Use mm minute syntax

.travis.yml, config/karma.conf.developer.js, config/karma.conf.travis.js, elcid/__init__.py, elcid/assets/js/elcid/services/flow.js, elcid/assets/js/elcidtest/flow.service.test.js, elcid/settings.py, elcid/templates/detail/inpatient.html, walkin/templates/detail/walkin.html
elCID implementation of new flows.
Fixes #669 
Bundled with this PR is combined JS&Python Coveralls reporting.
=> 669 flows2.0

elcid/migrations/0041_result.py, elcid/models.py, elcid/test/test_models.py, requirements.txt
=> added the results model, json field and test cases

walkin/static/js/walkin/controllers/walkin_hospital_number.js, walkin/static/js/walkintest/walkin_hospital_number.controller.test.js
=> pass through tags to walkin add patient

elcid/templates/add_episode_modal.html, elcid/templates/detail/inpatient.html
=> Add patient location

opat/templates/actions/next_stage.html
=> OPAT patients without a next stage shouldn't show a next stage button.

elcid/templates/forms/allergies_form.html
just adding short date to the dates displayed
=> add in short date

elcid/migrations/0048_remove_allergies_allergy_type.py, elcid/models.py, elcid/templates/forms/allergies_form.html, elcid/templates/partials/epma_modal_footer.html, requirements.txt
=> only show epma when we're sourcing from upstream

walkin/templates/modals/walkin/symptom_modal.html, walkin/tests/test_models.py, walkin/tests/test_views.py
depends on the add follow opal pull request
=> move the symptoms modal to the new form field setup

opat/patient_lists.py
=> Re-order OPAT lists

elcid/templates/referral/micro_haematology.html
=> add custom success message

elcid/models.py, elcid/templates/forms/demographics_form_pre_gloss.html, elcid/test/test_models.py
=> add in a if statement and a new modal if we're not in gloss

elcid/templates/referral/elcid_base_referral.html, elcid/templates/referral/ht_d_walk_in_clinic.html, elcid/templates/referral/micro_haematology.html, requirements.txt
walkin will now depend on the base template
=> 1164 referrals fixes

elcid/migrations/0016_create_consultant_singletons.py
we seemed to be missing an implied migration
=> add missing migration dependency

walkin/templates/modals/walkin/microbiology_input_modal.html
working example on http://elcid060.herokuapp.com/#/list/walkin-walkin_doctor
=> details needs to point at the editing.microbiology_input

opat/static/js/opat/controllers/opat_referral.js, research/static/js/research/controllers/research_hospital_number.js, walkin/static/js/walkin/controllers/walkin_hospital_number.js, walkin/static/js/walkintest/walkin_hospital_number.controller.test.js
…that use the OPAL AddEpisodeCtrl to not use options
=> Update add episode controllers 

elcid/assets/js/elcid/controllers/diagnosis_add_episode.js, elcid/assets/js/elcid/controllers/diagnosis_hospital_number.js, elcid/assets/js/elcidtest/diagnosis_add_episode.controller.test.js, elcid/assets/js/elcidtest/diagnosis_hospital_number.controller.test.js, opat/static/js/opat/controllers/opat_referral.js, research/static/js/research/controllers/research_hospital_number.js, walkin/static/js/walkin/controllers/walkin_hospital_number.js, walkin/static/js/walkintest/walkin_hospital_number.controller.test.js
... stacked PR - merge #1231 first
=> Diagnosis options refaactor

elcid/templates/forms/demographics_form.html, elcid/templates/forms/demographics_form_pre_gloss.html
bigger than maybe expected, I've taken the opportunity to remove the static tag,
if its been sourced from an external system, everything is static apart from place of birth
=> 1233 demographics title

elcid/templates/actions/presenting_complaint.html
=> Update resolves for final diagnosis action.

walkin/patient_lists.py
=> Add allergies to the walkin nurse list

elcid/templates/records/allergies.html
=> Display question mark before drug for provisional allergies

opat/templates/discharge_opat_episode_modal.html
=> Use a consistent word - refuse not reject for OPAT flow

elcid/templates/detail/inpatient.html
=> Add diagnosis to detail page

elcid/test/test_patient_lists.py, infectiousdiseases/patient_lists.py
=> First pass weekend list for tropical/immune/id

opat/templates/discharge_opat_episode_modal.html
=> Even more things were called reject - rename them to refuse

CHANGELOG.md, opat/patient_lists.py, walkin/patient_lists.py
Now that we have tabbed list groups, let's use them !
=> Tabbed list groups

elcid/test/test_views.py, elcid/urls.py, microhaem/tests/test_views.py
I know this isn't a big worry, but I noticed this didn't have permissioning when I was going through coverralls
=> bulk create user shoud be authentiated

elcid/assets/js/elcid/controllers/diagnosis_discharge.js, elcid/templates/elcid/modals/diagnosis_discharge.html
depends on https://github.com/openhealthcare/opal/pull/939
=> title to display name in the process steps

elcid/templates/elcid/modals/diagnosis_discharge.html
=> adding patient name to the diagnosis discharge header
